using System.Runtime.Serialization;

namespace LoremIpsum
{
    /// <summary>
    /// The main model for the Lorem Ipsum service
    /// </summary>
    public class LoremIpsum
    {
        public Feed Feed { get; set; }
    }

    /// <summary>
    /// The main object from the feed
    /// </summary>
    [DataContract]
    public class Feed
    {
        /// <summary>
        /// The Lorem Ipsum text generated by the service
        /// </summary>
        [DataMember(Name ="lipsum")]
        public string Lipsum { get; set; }

        /// <summary>
        /// What was generated (words, paragraphs, bytes)
        /// </summary>
        [DataMember(Name = "generated")]
        public string Generated { get; set; }

        /// <summary>
        /// The link to visit to donate to the project
        /// </summary>
        [DataMember(Name = "donatelink")]
        public string DonateLink { get; set; }

        /// <summary>
        /// A link that should be used when giving attribution for the service
        /// </summary>
        [DataMember(Name = "creditlink")]
        public string CreditLink { get; set; }

        [DataMember(Name = "creditname")]
        public string CreditName { get; set; }
    }

}
